### ISSUE TITLE
Paypal tutorial for the current version of Cartridge?

### ISSUE THREAD

**Issue by pingyangtiaer** [henri-hulski/cartridge_braintree#10] opened 2018-01-16 20:02 UTC
Would you please provide a tutorial on how to use the Paypal for the current version of CartRidge?

**Comment by henri-hulski** [comment] 2018-01-16 20:37
I think the documentation is up to date. There wasn't a new Cartridge release recently.

**Comment by pingyangtiaer** [comment] 2018-01-16 21:50
Would you please give me some hints on how to switching to the paypal payment OR add paypal payment option for using the current version (with the pip install -U cartridge installation)?
Looking forward to hearing from you.

**Comment by henri-hulski** [comment] 2018-01-16 22:16
Cartridge_braintree supports PayPal and credit cards.

https://github.com/henri-hulski/cartridge_braintree/blob/master/README.rst

**Comment by pingyangtiaer** [comment] 2018-01-18 20:12
Thank you henri, I got your instructions and it worked all the way until I click the "next" to complete the transaction, I got an error : 
"
Request Method: | POST
-- | --
http://18.216.209.171:5000/shop/checkout/
1.10.8
error
[Errno 111] Connection refused
/usr/lib/python2.7/socket.py in create_connection, line 575
/usr/bin/python
2.7.12
['/home/ubuntu/cartridge/braintreeprj',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/home/ubuntu/.local/lib/python2.7/site-packages',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages'
"
I just put my program on a ec2 ubuntu server, do you have some idea how can I make it into production(am I missing work around)?

**Comment by bld2104** [comment] 2018-01-18 22:52
I am getting a similar error! 
<img width="1397" alt="screen shot 2018-01-18 at 5 35 50 pm" src="https://user-images.githubusercontent.com/7794512/35125628-5e024f88-fc78-11e7-902a-5dfd03b02a19.png">

**Comment by henri-hulski** [comment] 2018-01-18 23:55
My prove of concept is [here](https://hempis.openhomeo.info).
It's connected with the Braintree and PayPal sandbox. So just try it out. 
Cannot reproduce the problem.

**Comment by henri-hulski** [comment] 2018-01-20 19:51
@bld2104 The error looks not really similar.  ;)
I'm not sure if Cartridge and Django 1.10 work under Python 3.6.
Officially only Python 2.7, 3.4 and 3.5 are supported.

**Comment by bld2104** [comment] 2018-01-20 19:52
@henri-hulski ah that's probably the problem then. Thanks for the response.

**Comment by henri-hulski** [comment] 2018-01-20 19:55
It says AuthenticationError.
So could also be something else. Difficult to say from here.

**Comment by pingyangtiaer** [comment] 2018-01-21 05:14
I am still stuck over here, I am one question on step 5:
"If you are overriding the templates in your own apps, then be sure to include the relevant braintreejs.html template.", how can I make sure those files, what are those files? when I went into the (\Lib\site-packages\cartridge_braintree\templates directory, I saw the shop folder which consists four files checkout.html, payment.html and braintreejs.html and payment_fields (in the includes directory), do I need to manually copy those files and overwrite the  files in the shop folder?
 For step 7, I used the alternative way but I don't know how to do the first method. how to activate them in the Admin Site Settings and set the currency to use with PayPal? It might be my problem.
Thank you so much for your respond.
BTW, I am quite interested in your website, I am curious how did you make it happen. If possible I would like to discuss with you on the hangout(pingyang.whu@gmail.com) or skype(pingyang.whu1).

**Comment by henri-hulski** [comment] 2018-01-21 12:44
About the templates, like this it works out of the box. For override it you have to look at the Mezzanine docs. I'm not working anymore with Django / Mezzanine, so don't remember exactly.

If you don't use the alternative method in 7., there should show up a entry in the Admin settings. When using the alternative method that entry doesn't show up. 

If you have questions to the website we can use telegram. BTW I think the site is down atm but should be fixed today.

**Closed as completed** 2022-02-18 23:35 UTC
